apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nx-private-cloud
  labels:
    version: v1
    app: nx-private-cloud
  name: nx-private-cloud-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      version: v1
      app: nx-private-cloud
  template:
    metadata:
      labels:
        version: v1
        app: nx-private-cloud
      annotations:
        logging.kubesphere.io/logsidecar-config: '{}'
    spec:
      containers:
        - name: container-45pv80
          imagePullPolicy: Always
          image: nxprivatecloud/nxcloud
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 8081
            initialDelaySeconds: 90
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 8081
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 8081
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: host-time
              mountPath: /etc/localtime
              readOnly: true
            - name: volume-2wx2hi
              readOnly: false
              mountPath: /data
          env:
            - name: ADMIN_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: nx-private-cloud-dict
                  key: ADMIN_PASSWORD
            - name: GITHUB_AUTH_CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: nx-private-cloud-dict
                  key: GITHUB_AUTH_CLIENT_ID
            - name: GITHUB_AUTH_CLIENT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: nx-private-cloud-dict
                  key: GITHUB_AUTH_CLIENT_SECRET
            - name: GITHUB_WEBHOOK_SECRET
              valueFrom:
                configMapKeyRef:
                  name: nx-private-cloud-dict
                  key: GITHUB_WEBHOOK_SECRET
            - name: NX_CLOUD_APP_URL
              valueFrom:
                configMapKeyRef:
                  name: nx-private-cloud-dict
                  key: NX_CLOUD_APP_URL
          ports:
            - name: http-8081
              protocol: TCP
              containerPort: 8081
              servicePort: 8081
      serviceAccount: default
      initContainers: []
      volumes:
        - hostPath:
            path: /etc/localtime
            type: ''
          name: host-time
        - name: volume-2wx2hi
          persistentVolumeClaim:
            claimName: nx-private-cloud-data
      imagePullSecrets: null
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
---
apiVersion: v1
kind: Service
metadata:
  namespace: nx-private-cloud
  labels:
    version: v1
    app: nx-private-cloud
  annotations:
    kubesphere.io/serviceType: statelessservice
    kubesphere.io/alias-name: Nx Private Cloud
    kubesphere.io/description: 私有 Nx 云服务
  name: nx-private-cloud
spec:
  sessionAffinity: None
  selector:
    app: nx-private-cloud
  ports:
    - name: http-8081
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 86400
